name: Build Installer

on:
  workflow_dispatch: 

jobs:
  build:
    name: Build the Inno Setup Installer
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

       - name: Generate release tag
        id: generate_tag
        run: |
          $releaseTag = (Get-Date).ToString('yy.MM.dd')
          echo "RELEASE_TAG=$releaseTag" >> $env:GITHUB_ENV

      - name: Prepare for testing (x64 only)
        run: |
          if (Test-Path -Path .\testing) {
            Copy-Item -Path .\testing\* -Destination .\input -Recurse -Force
          } else {
            Write-Error "The 'testing' directory does not exist."
          }
          (Get-Content "Setup.iss") | 
            ForEach-Object { $_ -replace '1.0.0', '${{ env.RELEASE_TAG }}' } | 
            Set-Content "Setup.iss"
        shell: pwsh

      - name: Compile Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: Setup.iss
          options: /O+

      - name: Upload installer artifacts
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: output/*.exe
          if-no-files-found: error
